apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template: 
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backserver
        image: chellyahmed/lab23backend:1.0.1 # Fill in: your-backend-image:tag
        env:
        - name: DB_HOST
          value: mysql-service
        - name: DB_USER
          value: root
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret # Name of the secret file
              key: MYSQL_ROOT_PASSWORD # Name fo the value in the secret file, in this case it is the same name
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret # Name of the secret file
              key: MYSQL_DATABASE # Name fo the value in the secret file, in this case it is the same name
        ports:
        - containerPort: 3000