apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
   app: backend
  ports:
  - port: 5000
    targetPort: 3000
  # We will link port 5000 of the service to port 3000 of the container


# To know the ip of the service to test it with curl, we can use the command:
# kubectl get svc backend-service