apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql-db
  ports:
    - port: 3306  # used to be 3005 but we changed it later.
      targetPort: 3306
      # Will link target port 3306 in my pod to 3005 in the service (host) so external peeps connect to 3005 to communicate with 3306 in pod
