apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment # Name of the deployment
spec:
  replicas: 1
  selector:
    matchLabels: # Connects resources with this label (for the deployment)
      app: mysql-db
  template:
    metadata:
      labels: # Label of the pod 
        app: mysql-db
    spec:
      containers:
      - name: db
        image: chellyahmed/lab23db:1.0.1
        env:
        - name: MYSQL_ROOT_PASSWORD # Env var in my code
          valueFrom:
            secretKeyRef:
              name: mysql-secret # Name of the secret file
              key: MYSQL_ROOT_PASSWORD # Name fo the value in the secret file, in this case it is the same name
        - name: USELESS_TEST_VAR
          value: WHATEVER
        ports:
        - containerPort: 3306
